export const questions = [
  {
    question: "Can you describe a previous project where you served as a Product Manager, detailing your key responsibilities and the outcomes?",
    answer: "As a Product Manager at edunext, I identified a recurring issue in the Open edX platform where clients struggled with effectively integrating external tools using LTI (Learning Tools Interoperability). Recognizing the impact this had on user experience and platform adoption, I led the development of a solution that significantly improved LTI integration, making it more user-friendly and efficient. My responsibilities included identifying the problem, defining product requirements, coordinating with the development team, and validating the solution through client testing. The outcome was a successful sale of the solution to Axim.org, an organization that works with clients as Harvard University and the MIT. That resolt in over $40,000 in revenue and solidifying our relationship with the client."
  },
  {
    question: "Have you been involved in AI implementation projects before? If so, can you provide an example and describe the project's scope, your role, and the final results?",
    answer: "Yes, I am currently involved in an AI implementation project where we are developing a product designed to assist teachers in moderating debates and classes with their students. The scope of this project includes creating an AI-driven tool that can analyze and provide real-time feedback during discussions, helping teachers manage and guide conversations more effectively. My role involves overseeing the product development process, defining the AI’s capabilities, and ensuring it meets the needs of educators. While this is still a work in progress, at a company level, our objective is to sell this solution to some of our key clients, enhancing their educational offerings and driving value for both the clients and our organization."
  },
  {
    question: "How do you develop project plans, timelines, and budgets? Can you share an example of how you managed these elements to keep a project on track?",
    answer: "When developing project plans, timelines, and budgets, I always start by thoroughly understanding the problem we want to solve. This involves studying the issue in depth and then defining a clear objective that we want to achieve. From there, I create a business case where I explore possible solutions that could lead us to that objective. For each potential solution, I define a Minimum Viable Product (MVP) that can be developed and launched within a sprint. Together with the technical team, we estimate the timeline for both the MVP and the complete solution, which also helps us determine the costs involved. The business case also includes revenue projections based on preliminary tests we conduct beforehand. Once the business case is ready, I present it, and if it’s approved, we move into the development phase. However, the business case can sometimes fall through if the costs don’t align or if we discover that we’re not addressing the right problem. For example, while working on a project aimed at reducing the number of clients in payment arrears, we discovered during the business case analysis that the problem could actually be solved by manually addressing the arrears of just two key clients, without the need for a full-scale development. This realization allowed us to avoid unnecessary costs and redirected our focus to other problems."
  },
  {
    question: "How do you ensure clear communication and collaboration among stakeholders, and can you provide an example of a challenging situation you managed successfully?",
    answer: "I ensure clear communication and collaboration among stakeholders by maintaining asynchronous and transparent communication channels. This approach allows everyone to stay informed and engaged without the need for constant meetings. One challenging situation I successfully managed involved mediating between an open-source community and a university that wanted to implement changes to the core of the open-source software. The community was initially resistant and skeptical about the proposed changes. To address this, I created a detailed post explaining the changes and backed it up with all the data I could gather in collaboration with the university. We had to revise the initial solution, incorporating feedback from key community members. In the end, we reached a consensus where both the community and the university were satisfied with the outcome."
  },
  {
    question: "What strategies do you use to organize and lead teams, and can you provide an example of motivating a team to achieve a project goal?",
    answer: "When organizing and leading teams, I focus on setting a clear, measurable objective that everyone can align around. I ensure the team is engaged by regularly showing them the progress we’re making towards that goal through measurable results during each iteration. This keeps everyone motivated and focused on the end goal. A great example related to the situation I mentioned earlier is when I was mediating between an open-source community and a university. I kept the team motivated by continuously sharing how many community members had started supporting the project, which reinforced the belief that we were on the right track and that the project would succeed."
  },
  {
    question: "Describe a time when a project you were managing encountered a significant issue. How did you address the problem, and what was the outcome?",
    answer: "In one of the projects I managed, there was a significant issue where stakeholders were divided between two potential solutions, which had stalled the project for a considerable time. When I took over, I prioritized listening to both sides and then tested the proposed solutions with real users. Ultimately, we chose the solution that performed best. This decision was based on real data, which helped build confidence among all stakeholders and allowed the project to move forward successfully."
  },
  {
    question: "How do you manage multiple high-priority projects, and can you share an example of a time you successfully handled several at once?",
    answer: "When managing multiple high-priority projects, I focus on organizing the execution by sprints. This approach allows me to stagger the different phases of each project. For example, while one project is progressing through its development phase, the other can be advancing through its planning phase. Once a first version of the initial project is delivered, we begin measuring its impact and performance while the second project moves into development. By the time the second project is completed and enters its measurement phase, we already have data from the first project to iterate and make improvements. This structured approach ensures that both projects move forward efficiently without sacrificing quality."
  }
];